services:
  database:
    image: postgres
    container_name: database_article
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=articles
      - POSTGRES_DB=articles
    volumes:
      - pgdata:/data/postgres

# app:
#   build: .
#   container_name: articles
#   restart: always
#   ports:
#     - 3333:3333
#   volumes:
#     - .:/usr/app
#   links:
#     - database
#   depends_on:
#     - database

volumes:
  pgdata:
    driver: local
